version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - $DB_PORT:$DB_PORT
    env_file:
      - .env
  api:
    build: ./api
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:$PORT"
    ports:
      - $PORT:$PORT
    volumes:
      - ./api:/api
    env_file:
      - .env
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    volumes:
      - ./client:/usr/app
      - "/usr/app/node_modules"
    env_file:
      - .env
    depends_on:
      - api