version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
  api:
    build: ./api
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:$PORT"
    ports:
      - 8000:8000
    volumes:
      - ./api:/api
    env_file:
      - .env
    depends_on:
      - db
  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/usr/app
      - "/usr/app/node_modules"
    env_file:
      - .env
    depends_on:
      - api