name: CI (api)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  health-check-job:
    runs-on: ubuntu-latest

    steps:
    - name: code checkout 
      uses: actions/checkout@v2

    - name: check python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./api/requirements.txt

    - name: api build
      run: |
        python -m pip install --upgrade pip
        docker-compose up --build -d api

    - name: tests
      run: docker-compose run api python manage.py test

    - name: sonarcloud
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        