name: CI (client)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:

  health-check-job:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.15.5"

      - name: build
        run: docker-compose up -d client

      - name: tests
        run: docker-compose run client quasar test --unit jest

  code_quality_with_sonar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: sonarcloud scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: client
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}